dmotion:
    motor:
      1.zf : 1
      1.k  : 4096
      1.lb : 0
      1.ub : 4096

      2.zf : -1
      2.k  : 4096
      2.lb : 0
      2.ub : 4096

      3.zf : -1
      3.k  : 4096
      3.lb : 0
      3.ub : 4096

      4.zf : -1
      4.k  : 4096
      4.lb : 0
      4.ub : 4096

      5.zf : -1
      5.k  : 4096
      5.lb : 0
      5.ub : 4096

      6.zf : 1
      6.k  : 4096
      6.lb : 0
      6.ub : 4096

      7.zf : -1
      7.k  : 4096
      7.lb : 0
      7.ub : 4096

      8.zf : -1
      8.k  : 4096
      8.lb : 0
      8.ub : 4096

      9.zf : 1
      9.k  : 4096
      9.lb : 0
      9.ub : 4096

      10.zf : -1
      10.k  : 4096
      10.lb : 0
      10.ub : 4096


      11.k  : 4096
      11.lb : 0
      11.ub : 4096

      12.zf : 1
      12.k  : 4096
      12.lb : 0
      12.ub : 4096

      13.zf : -1
      13.k  : 4096
      13.lb : 0
      13.ub : 4096

      14.zf : -1
      14.k  : 4096
      14.lb : 0
      14.ub : 4096

      15.zf : 1
      15.k  : 4096
      15.lb : 0
      15.ub : 4096

      16.zf : -1
      16.k  : 4096
      16.lb : 0
      16.ub : 4096

      17.zf : 1
      17.k  : 4096
      17.lb : 0
      17.ub : 4096

      18.zf : 1
      18.k  : 4096
      18.lb : 0
      18.ub : 4096

      19.zf : 1
      19.k  : 1024
      19.lb : 0
      19.ub : 1024

      20.zf : 1
      20.k  : 4096
      20.lb : 0
      20.ub : 4096
