#pragma once

namespace dconstant {
namespace geometry {
// Field geometry in cm, refer to RoboCup Humanoid Rules
const int fieldLength = 900;
const int fieldWidth = 600;
const int goalDepth = 60;
const int goalWidth = 260;
const int goalHeight = 180;
const int goalAreaLength = 100;
const int goalAreaWidth = 500;
const int penaltyMarkDistance = 210;
const int centerCircleDiameter = 150;
const int borderStripWidth = 70;
const int lineWidth = 5;
}

namespace network {
// Generated by https://www.random.org/
const int robotBroadcastAddressBase = 48175;
const int monitorBroadcastAddressBase = 26333;
}

namespace robotSize {
const int width = 30;
const int height= 20;
}

namespace ballSize {
const int diameter = 15;
}
}
